# Generated by Django 4.1 on 2022-12-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="price",
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
