# Generated by Django 4.1 on 2022-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_plan_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plantype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="")),
                ("duration", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=300)),
            ],
        ),
    ]
