# Generated by Django 4.1 on 2022-12-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0003_plantype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plantype",
            old_name="desc",
            new_name="description",
        ),
    ]
